# Generated by Django 3.1.4 on 2021-05-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_squashed_0011_auto_20210504_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['city'], 'verbose_name': 'city', 'verbose_name_plural': 'cities'},
        ),
    ]
