# Generated by Django 3.1.4 on 2022-01-21 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-updated_at'], 'permissions': [('change_customer_name', 'Can change the name of customers'), ('change_customer_city', 'Can change the city of customers')], 'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
    ]
