# Generated by Django 3.1.4 on 2021-05-05 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_squashed_0003_auto_20210504_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['nick'], 'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
    ]
