# Generated by Django 3.1.4 on 2022-01-21 20:16

from django.db import migrations
from django.db.models import AutoField, CharField


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20220121_2248'),
    ]

    operations = [
    ]

    migrations.RunSQL(
        sql=[
        "ALTER TABLE public.customer_city DROP CONSTRAINT customer_city_pkey;",
        "ALTER TABLE public.customer_city ADD COLUMN id SERIAL PRIMARY KEY;"
        "ALTER TABLE public.customer_city ALTER COLUMN pindex DROP NOT NULL;"
        "ALTER TABLE public.customer_city ADD CONSTRAINT customer_city_pkey PRIMARY KEY (id);"
        ],
        reverse_sql=[
        "ALTER TABLE public.customer_city DROP CONSTRAINT customer_city_pkey;",
        "ALTER TABLE public.customer_city DROP COLUMN id;",
        "ALTER TABLE public.customer_city ALTER COLUMN pindex SET NOT NULL;",
        "ALTER TABLE public.customer_city ADD PRIMARY KEY (pindex);",
        ],
        state_operations=[
        migrations.RemoveIndex(model_name='City', name='customer_city_pkey'),
        migrations.AlterField(
        model_name='City', name='pindex',
        field=CharField(max_length=6, null=True, blank=True)
        ),
        migrations.AddField(
        model_name='City', name='id',
        field=AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ]
    )
