# Generated by Django 3.2.2 on 2021-05-07 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['nick'], 'permissions': [('change_customer_name', 'Can change the name of customers'), ('change_customer_city', 'Can change the city of customers')], 'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
    ]
