# Generated by Django 3.1.4 on 2022-01-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_change_primary_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='pindex',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='pindex'),
        ),
    ]
