# Generated by Django 3.1.4 on 2022-01-21 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20220122_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city1',
            field=models.ForeignKey(blank=True, db_column='city_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities1', to='customer.city', verbose_name='city'),
        ),
    ]
