# Generated by Django 3.1.4 on 2022-01-21 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_customer_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='city1',
            new_name='city',
        ),
    ]
