# Generated by Django 3.1.4 on 2022-01-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20220122_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='citykey',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='opsname',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
