# Generated by Django 3.1.4 on 2022-01-21 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20220122_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='citykey',
        ),
    ]
