# Generated by Django 3.1.4 on 2022-01-22 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_remove_city_citykey'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='city',
            index_together={('city', 'pindex')},
        ),
    ]
