# Generated by Django 3.1.4 on 2021-12-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contents',
            field=models.PositiveIntegerField(blank=True, choices=[(None, '-'), (1, 'with lycra'), (2, '100% cotton')], null=True, verbose_name='contents'),
        ),
        migrations.AlterField(
            model_name='product',
            name='threads',
            field=models.PositiveIntegerField(blank=True, choices=[(None, '-'), (1, 'two threads'), (2, 'three threads')], null=True, verbose_name='threads'),
        ),
    ]
