# Generated by Django 3.1.4 on 2022-02-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220121_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_at'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='product',
            name='fleece',
            field=models.BooleanField(blank=True, null=True, verbose_name='fleece'),
        ),
        migrations.AlterField(
            model_name='product',
            name='contents',
            field=models.PositiveIntegerField(blank=True, choices=[(None, '----'), (0, 'with lycra'), (1, '100% cotton')], null=True, verbose_name='contents'),
        ),
        migrations.AlterField(
            model_name='product',
            name='threads',
            field=models.PositiveIntegerField(blank=True, choices=[(None, '----'), (0, 'two threads'), (1, 'three threads')], null=True, verbose_name='threads'),
        ),
    ]
