# Generated by Django 3.1.4 on 2021-12-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211225_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='threads',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'two threads'), (2, 'three threads')], null=True, verbose_name='threads'),
        ),
    ]
