# Generated by Django 3.1.4 on 2021-05-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contents',
            field=models.PositiveIntegerField(blank=True, choices=[(None, ''), (1, 'with lycra'), (2, '100% cotton')], null=True, verbose_name='contents'),
        ),
    ]
