# Generated by Django 3.1.4 on 2021-05-05 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contents',
            field=models.PositiveIntegerField(blank=True, choices=[(None, '(Unknown)'), (1, 'with lycra'), (2, '100% cotton')], null=True, verbose_name='contents'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.producttype', verbose_name='product_type'),
        ),
    ]
