# Generated by Django 3.1.4 on 2021-05-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210506_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='threads',
            field=models.PositiveIntegerField(blank=True, choices=[(None, '(Unknown)'), (1, 'two threads'), (2, 'three threads')], null=True, verbose_name='threads'),
        ),
        migrations.AlterField(
            model_name='product',
            name='contents',
            field=models.PositiveIntegerField(blank=True, choices=[(None, '(Unknown)'), (1, 'with lycra'), (2, '100% cotton')], null=True, verbose_name='contents'),
        ),
    ]
