# Generated by Django 3.2.2 on 2021-05-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_item', '0002_auto_20210505_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
