# Generated by Django 3.1.4 on 2022-01-04 11:24

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('post_cost', models.PositiveIntegerField(blank=True, default=0, verbose_name='post_cost')),
                ('packet', models.PositiveIntegerField(blank=True, choices=[(None, '(Unknown)'), (25, '25'), (27, '27'), (50, '50'), (55, '55'), (72, '72'), (85, '85')], null=True, verbose_name='packet')),
                ('delivery_type', models.IntegerField(blank=True, choices=[(None, '(Unknown)'), (0, 'Post of Russia'), (1, 'Business Lines'), (2, 'PEK'), (3, 'GTD (Whale)'), (4, 'Energy'), (5, 'Railway Expedition'), (6, 'Ratek'), (7, 'Baikal Service'), (8, 'SDEK Parcel')], null=True, verbose_name='delivery_type')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('gift', models.CharField(blank=True, max_length=255, verbose_name='gift')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-created_at'],
            },
            managers=[
                ('orders', django.db.models.manager.Manager()),
            ],
        ),
    ]
