# Generated by Django 3.1.4 on 2021-05-05 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_squashed_0003_auto_20210504_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
    ]
