# Generated by Django 3.1.4 on 2022-01-21 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_products'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
            ],
        ),
    ]
