# Generated by Django 3.1.4 on 2021-12-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_item', '0002_auto_20211225_1637'),
        ('product', '0002_auto_20211225_1637'),
        ('order', '0002_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='post_cost',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='post_cost'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, through='order_item.OrderItem', to='product.Product'),
        ),
    ]
